---
  id: "sentinel1"
  arco: False
  collection: "sentinel1"
  compute: "awslambda"
  sns: "arn:aws:sns:eu-central-1:214830741341:SentinelS1L1C"
  inventory_location: "s3://sentinel-inventory/sentinel-s1-l1c/sentinel-s1-l1c-inventory/hive/dt=2022-11-16-01-00/"
  initial_chunk: "2022-4-20"
